[tool.poetry]
name = "data-cleaner"
version = "0.1.0"
description = "Add your description here"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false
requires-python = ">=3.12"
dependencies = []
